In [1]:
##
#   Junta as bases do CNIR e DITR por meio do nirf
##
import numpy as np
import pandas as pd
import os

In [2]:
cnirs = pd.read_pickle('..\\DADOS\\cnirs_trein.pickle')
ditr2020 = pd.read_pickle('..\\DADOS\\ditr2020.pickle')

In [3]:
cnirs_ditr2020 = cnirs.merge(ditr2020, left_on='cnir.nirf', right_on='ditr2020.nirf', how='inner')
cnirs_ditr2020.to_pickle('..//DADOS//cnirs_DITR2020.pickle')
cnirs_ditr2020

,cnir.codigoCnir,cnir.municipio,cnir.areaTotal,cnir.ni,cnir.codigoIncra,cnir.nirf,ditr2020.nirf,ditr2020.codigoIncra,ditr2020.ni,ditr2020.areaTotal,ditr2020.municipio
0,461126,1100015,35791.1145,29915619804,0010900016277,15955257,15955257,0010900016277,29915619804,36075.0,1100015
1,490266,1100015,3040.6686,38368102987,0012280119839,40738868,40738868,0012280119839,38368102987,3040.6,1100015
2,462245,1100015,2227.8982,42632188849,0010901351940,41931661,41931661,0010901351940,42632188849,2227.8,1100015
3,482468,1100015,2115.3528,62498045872,0011710115925,33902925,33902925,NAO INFORMADO,62498045872,1004.0,1100015
4,482556,1100015,2033.3952,42632188849,0011710137651,42001382,42001382,0011710137651,42632188849,2033.3,1100015
...,...,...,...,...,...,...,...,...,...,...,...
2085787,4611699,5300108,15.8000,04088778715,9410180507686,10887636,10887636,9410180507686,04088778715,15.8,5300108
2085788,4613422,5300108,15.8000,12650625104,9410181023690,15898709,15898709,9410181023690,12650625104,14.5,5300108
2085789,6448944,5300108,15.7332,47205342449,9999893725873,89134133,89134133,NAO INFORMADO,47205342449,17.3,5300108
2085790,4612125,5300108,15.6800,36670588100,9410180605181,10893776,10893776,9410180605181,36670588100,17.6,5300108
2085791,4611309,5300108,15.5000,00980242134,9410180405417,10889469,10889469,9410180405417,00980242134,15.5,5300108

In [4]:
## Criando um subconjunto de aprendizado
cj_aprend = pd.read_pickle('..//DADOS//cnirs_DITR2020.pickle')

# Criando colunas igualdade (ig.xxxxx)
cj_aprend['ig.ni'] = cj_aprend['cnir.ni'] == cj_aprend['ditr2020.ni']
cj_aprend['ig.codigoIncra'] = cj_aprend['cnir.codigoIncra'] == cj_aprend['ditr2020.codigoIncra']
cj_aprend['ig.municipio'] = cj_aprend['cnir.municipio'] == cj_aprend['ditr2020.municipio']

# Criando coluna de variaÃ§Ã£o da Ã¡rea entre CNIR e DITR2019
#cj_aprend[['cnir.areaTotal', 'ditr2019.areatotal']] = cj_aprend[['cnir.areaTotal', 'ditr2019.areatotal']].apply(pd.to_numeric)
cj_aprend['dif'] = np.where(cj_aprend['cnir.areaTotal'] > cj_aprend['ditr2020.areaTotal'], 
             (cj_aprend['cnir.areaTotal'] - cj_aprend['ditr2020.areaTotal']) / cj_aprend['cnir.areaTotal'], 
             (cj_aprend['ditr2020.areaTotal'] - cj_aprend['cnir.areaTotal']) / cj_aprend['ditr2020.areaTotal'])  
#reduzindo a quantidade  de valores para simplificar o aprendizado
cj_aprend['dif'] = cj_aprend['dif'].apply(lambda x:int(x * 100))

cj_aprend

,cnir.codigoCnir,cnir.municipio,cnir.areaTotal,cnir.ni,cnir.codigoIncra,cnir.nirf,ditr2020.nirf,ditr2020.codigoIncra,ditr2020.ni,ditr2020.areaTotal,ditr2020.municipio,ig.ni,ig.codigoIncra,ig.municipio,dif
0,461126,1100015,35791.1145,29915619804,0010900016277,15955257,15955257,0010900016277,29915619804,36075.0,1100015,True,True,True,0
1,490266,1100015,3040.6686,38368102987,0012280119839,40738868,40738868,0012280119839,38368102987,3040.6,1100015,True,True,True,0
2,462245,1100015,2227.8982,42632188849,0010901351940,41931661,41931661,0010901351940,42632188849,2227.8,1100015,True,True,True,0
3,482468,1100015,2115.3528,62498045872,0011710115925,33902925,33902925,NAO INFORMADO,62498045872,1004.0,1100015,True,False,True,52
4,482556,1100015,2033.3952,42632188849,0011710137651,42001382,42001382,0011710137651,42632188849,2033.3,1100015,True,True,True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2085787,4611699,5300108,15.8000,04088778715,9410180507686,10887636,10887636,9410180507686,04088778715,15.8,5300108,True,True,True,0
2085788,4613422,5300108,15.8000,12650625104,9410181023690,15898709,15898709,9410181023690,12650625104,14.5,5300108,True,True,True,8
2085789,6448944,5300108,15.7332,47205342449,9999893725873,89134133,89134133,NAO INFORMADO,47205342449,17.3,5300108,True,False,True,9
2085790,4612125,5300108,15.6800,36670588100,9410180605181,10893776,10893776,9410180605181,36670588100,17.6,5300108,True,True,True,10
2085791,4611309,5300108,15.5000,00980242134,9410180405417,10889469,10889469,9410180405417,00980242134,15.5,5300108,True,True,True,0

In [5]:
# EliminaÃ§Ã£o das colunas desnecessÃ¡rias
del cj_aprend['cnir.nirf']
del cj_aprend['cnir.municipio']
del cj_aprend['cnir.areaTotal']
del cj_aprend['cnir.ni']
del cj_aprend['cnir.codigoIncra']

del cj_aprend['ditr2020.ni']
del cj_aprend['ditr2020.areaTotal']
del cj_aprend['ditr2020.municipio']

cj_aprend.to_pickle('..//DADOS//cj_aprend.pickle')