In [1]:
##
#   Faz o join entre o CNIR e a DITR2020 e
#   e cria o conjunto de dados falsos
##
import numpy as np
import pandas as pd
import os

In [2]:
# Conjunto de cnirs vinculados. Esses registros serão considerados como Verdadeiro.
cnirs_v = pd.read_pickle('..\\DADOS\\cnirs_trein.pickle') 
# Conjunto de toas as DITRs do ano base 2020
ditr2020 = pd.read_pickle('..\\DADOS\\ditr2020.pickle')

In [3]:
# cnirs_ditr2020_v é o conjunto de dados que foram classificados como corretos (class = True)
cnirs_ditr2020_v = cnirs_v.merge(ditr2020, left_on='cnir.nirf', right_on='ditr2020.nirf', how='inner')
cnirs_ditr2020_v['class'] = True
cnirs_ditr2020_v.to_pickle('..//DADOS//v2_cnirs_DITR2020_v.pickle')
cnirs_ditr2020_v

,cnir.codigoCnir,cnir.municipio,cnir.areaTotal,cnir.ni,cnir.codigoIncra,cnir.nirf,ditr2020.nirf,ditr2020.codigoIncra,ditr2020.ni,ditr2020.areaTotal,ditr2020.municipio,class
0,461126,1100015,35791.1145,29915619804,0010900016277,15955257,15955257,0010900016277,29915619804,36075.0,1100015,True
1,490266,1100015,3040.6686,38368102987,0012280119839,40738868,40738868,0012280119839,38368102987,3040.6,1100015,True
2,462245,1100015,2227.8982,42632188849,0010901351940,41931661,41931661,0010901351940,42632188849,2227.8,1100015,True
3,482468,1100015,2115.3528,62498045872,0011710115925,33902925,33902925,NAO INFORMADO,62498045872,1004.0,1100015,True
4,482556,1100015,2033.3952,42632188849,0011710137651,42001382,42001382,0011710137651,42632188849,2033.3,1100015,True
...,...,...,...,...,...,...,...,...,...,...,...,...
2085787,4611699,5300108,15.8000,04088778715,9410180507686,10887636,10887636,9410180507686,04088778715,15.8,5300108,True
2085788,4613422,5300108,15.8000,12650625104,9410181023690,15898709,15898709,9410181023690,12650625104,14.5,5300108,True
2085789,6448944,5300108,15.7332,47205342449,9999893725873,89134133,89134133,NAO INFORMADO,47205342449,17.3,5300108,True
2085790,4612125,5300108,15.6800,36670588100,9410180605181,10893776,10893776,9410180605181,36670588100,17.6,5300108,True
2085791,4611309,5300108,15.5000,00980242134,9410180405417,10889469,10889469,9410180405417,00980242134,15.5,5300108,True

In [4]:
# cnirs_ditr2020_f é o conjunto de dados que foram classificados como incorretos (class = False)
cnirs_f = cnirs_v.copy(deep=True)
# o método join une os conjuntos a partir do index e produz um resultado quase aleatório
cnirs_ditr2020_f = cnirs_f.join(ditr2020, how='inner')
cnirs_ditr2020_f['class'] = False
cnirs_ditr2020_f.to_pickle('..//DADOS//v2_cnirs_DITR2020_f.pickle')
cnirs_ditr2020_f

,cnir.codigoCnir,cnir.municipio,cnir.areaTotal,cnir.ni,cnir.codigoIncra,cnir.nirf,ditr2020.nirf,ditr2020.codigoIncra,ditr2020.ni,ditr2020.areaTotal,ditr2020.municipio,class
3,461126,1100015,35791.1145,29915619804,0010900016277,15955257,07829736,6120810036548,55035183815,14.6,3539004,False
10,490266,1100015,3040.6686,38368102987,0012280119839,40738868,42323819,5021111017374,00518874796,6.6,3203353,False
11,462245,1100015,2227.8982,42632188849,0010901351940,41931661,73097195,NAO INFORMADO,02374473554,24.6,2906006,False
12,5182233,1100015,1872.8722,69144222149,9500849523703,69547688,38932997,NAO INFORMADO,29659590920,22.2,4219309,False
13,482468,1100015,2115.3528,62498045872,0011710115925,33902925,64092135,NAO INFORMADO,63847825291,74.0,1507458,False
...,...,...,...,...,...,...,...,...,...,...,...,...
5747787,4305391,5103106,1717.3000,55823246668,9010911635702,30846170,46600329,9501730460270,17423970697,510.2,3126901,False
5747791,4284287,5103106,1674.6615,10127828168,9010321285706,44441525,10400753,9500178038988,17134790010,11.5,4304713,False
5747792,4330168,5103106,1647.4410,10246603895,9012290015112,11781475,26409666,8150980261744,58280219900,10.0,4207759,False
5747794,90583,5103106,1613.0000,28933834753,0000271190328,42065313,40483720,0000272882509,35026677649,35.1,3148004,False
5747796,4767710,5103106,1607.5507,43356192191,9500332120323,02424800,68482345,NAO INFORMADO,05115329468,16.0,2702553,False

In [5]:
## Criando um subconjunto de aprendizado
cj_aprend = cnirs_ditr2020_v.append(cnirs_ditr2020_f)
print(cj_aprend.shape)

(4454349, 12)

In [6]:
# Criando colunas igualdade (ig.xxxxx)
cj_aprend['ig.ni'] = cj_aprend['cnir.ni'] == cj_aprend['ditr2020.ni']
cj_aprend['ig.codigoIncra'] = cj_aprend['cnir.codigoIncra'] == cj_aprend['ditr2020.codigoIncra']
cj_aprend['ig.municipio'] = cj_aprend['cnir.municipio'] == cj_aprend['ditr2020.municipio']

# Criando coluna de variação da área entre CNIR e DITR2019
#cj_aprend[['cnir.areaTotal', 'ditr2019.areatotal']] = cj_aprend[['cnir.areaTotal', 'ditr2019.areatotal']].apply(pd.to_numeric)
cj_aprend['dif'] = np.where(cj_aprend['cnir.areaTotal'] > cj_aprend['ditr2020.areaTotal'], 
             (cj_aprend['cnir.areaTotal'] - cj_aprend['ditr2020.areaTotal']) / cj_aprend['cnir.areaTotal'], 
             (cj_aprend['ditr2020.areaTotal'] - cj_aprend['cnir.areaTotal']) / cj_aprend['ditr2020.areaTotal'])  
#reduzindo a quantidade  de valores para simplificar o aprendizado
cj_aprend['dif'] = cj_aprend['dif'].apply(lambda x:int(x * 100))

cj_aprend

,cnir.codigoCnir,cnir.municipio,cnir.areaTotal,cnir.ni,cnir.codigoIncra,cnir.nirf,ditr2020.nirf,ditr2020.codigoIncra,ditr2020.ni,ditr2020.areaTotal,ditr2020.municipio,class,ig.ni,ig.codigoIncra,ig.municipio,dif
0,461126,1100015,35791.1145,29915619804,0010900016277,15955257,15955257,0010900016277,29915619804,36075.0,1100015,True,True,True,True,0
1,490266,1100015,3040.6686,38368102987,0012280119839,40738868,40738868,0012280119839,38368102987,3040.6,1100015,True,True,True,True,0
2,462245,1100015,2227.8982,42632188849,0010901351940,41931661,41931661,0010901351940,42632188849,2227.8,1100015,True,True,True,True,0
3,482468,1100015,2115.3528,62498045872,0011710115925,33902925,33902925,NAO INFORMADO,62498045872,1004.0,1100015,True,True,False,True,52
4,482556,1100015,2033.3952,42632188849,0011710137651,42001382,42001382,0011710137651,42632188849,2033.3,1100015,True,True,True,True,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5747787,4305391,5103106,1717.3000,55823246668,9010911635702,30846170,46600329,9501730460270,17423970697,510.2,3126901,False,False,False,False,70
5747791,4284287,5103106,1674.6615,10127828168,9010321285706,44441525,10400753,9500178038988,17134790010,11.5,4304713,False,False,False,False,99
5747792,4330168,5103106,1647.4410,10246603895,9012290015112,11781475,26409666,8150980261744,58280219900,10.0,4207759,False,False,False,False,99
5747794,90583,5103106,1613.0000,28933834753,0000271190328,42065313,40483720,0000272882509,35026677649,35.1,3148004,False,False,False,False,97
5747796,4767710,5103106,1607.5507,43356192191,9500332120323,02424800,68482345,NAO INFORMADO,05115329468,16.0,2702553,False,False,False,False,99

In [7]:
# Eliminação das colunas desnecessárias na aprendizagem
del cj_aprend['cnir.nirf']
del cj_aprend['cnir.municipio']
del cj_aprend['cnir.areaTotal']
del cj_aprend['cnir.ni']
del cj_aprend['cnir.codigoIncra']

del cj_aprend['ditr2020.ni']
del cj_aprend['ditr2020.areaTotal']
del cj_aprend['ditr2020.municipio']

cj_aprend.to_pickle('..//DADOS//v2_cj_aprend.pickle')